openapi: 3.0.0
paths:
  /api/v1/users:
    get:
      operationId: UsersController_create
      parameters: []
      responses:
        "200":
          description: ""
info:
  title: Title
  description: description
  version: "1.0"
  contact: {}
tags: []
servers: []
components:
  schemas: {}
