openapi: 3.0.0
paths:
  /api/v1/auth:
    put:
      operationId: AuthController_createAccount
      parameters: []
      requestBody:
        required: true
        content:
          application/json:
            schema:
              $ref: "#/components/schemas/CreateUserDTO"
      responses:
        "200":
          description: ""
    post:
      operationId: AuthController_loginAccount
      parameters: []
      requestBody:
        required: true
        content:
          application/json:
            schema:
              $ref: "#/components/schemas/LoginUserDTO"
      responses:
        "201":
          description: ""
    get:
      operationId: AuthController_autoLoginAccount
      parameters: []
      responses:
        "200":
          description: ""
      security:
        - refresh: []
info:
  title: Title
  description: description
  version: "1.0"
  contact: {}
tags: []
servers: []
components:
  schemas:
    CreateUserDTO:
      type: object
      properties: {}
    LoginUserDTO:
      type: object
      properties: {}
